### ISSUE TITLE
The scssphp dependency is using an unmaintained version

### ISSUE THREAD

**Issue by stof** [unb-libraries/dockworker#1]
The scssphp/scssphp dependency is using the `~1.1.0` constraint, which means `>=1.1.0 <1.2.0`.
As one of the maintainers of scssphp, I'm kindly warning you that the 1.1.x version of scssphp is not maintained anymore. We only provide support for the latest 1.x (currently at 1.9.0, with the 1.10.0 release coming soon). I encourage you to migrate to the latest version.

Side note: I haven't found any usage of the Scssphp library in that project. The only reference to scss I found is the [`ScssCompileTrait`](https://github.com/unb-libraries/dockworker/blob/b715fd37d00a004cccd6ddbe1ada50b92a77e089/src/ScssCompileTrait.php) which relies on a CLI executable to compile scss files. If that's the usage of scssphp, I suggest using the official Sass CLI provided by dart-sass. It will be a lot faster to execute than the pscss CLI of scssphp and more spec compliant (given that dart-sass is the reference implementation of the Sass language. Thus, the pscss executable is considered mostly as a debugging tool. It will be removed from the composer package for scssphp 2.0 (but it is still kept in 1.x for BC reasons) as code able to use a CLI tool to compiler Sass files should really use the faster official tool (we might still reconsider that decision if needed, by providing a separate scssphp/cli package instead, but that's not planned for now).

Note also that the `crunched` output is deprecated in scssphp 1.5+, keeping only `expanded` and `compressed` which are the output styles supported by dart-sass (crunched is very similar to compressed). So you might want to switch to `compressed` when updating.

**Comment by JacobSanford** [comment]
Hi Cristophe,

Firstly, thanks for the notification and time you have spent!

The dependency has been updated to the latest 1.x branch.

Thanks for the nudge towards dart-sass. We do prefer to depend on a packagist-provided compiler binary - our workflow's focus on minimal 'local workstation' dependencies strongly leverages packagist/composer to provide as many of the depencies as possible. I understand your intended use-case for the binary isn't aligned with that - and we can certainly adapt if you remove the tool from the package.

Warm regards,

Jake

**Comment by stof** [comment]
Well, we won't remove it in 1.x for sure. Adapting it for when we will release a 2.0 version will be up to you (we are not ready to release 2.0 yet anyway).

Anyway, I'm closing this issue as you now use a maintained version (I was on a hunt trying to understand while some older version of our package were still seeing significant usage in the stats)
